apiVersion: v1
kind: ConfigMap
metadata:
  name: thesis-scheduler-configmap
  labels:
    app: thesis-scheduler
data:
  DATABASE_URL: <connection URL> # e.g. "postgresql://USER:PASSWORD@HOST:PORT/DATABASE"

# data populated with environment variables as they are described
# in main README file